name = "tg-reader"
main = "src/index.ts"
compatibility_date = "2025-03-01"

[[r2_buckets]]
binding = "BACKUP_BUCKET"
bucket_name = "tg-reader-backup"

[triggers]
crons = ["0 3 * * *", "0 4 1 * *", "*/15 * * * *"]
#        daily backup   monthly chk   observer job runner
